// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {search} from '../models';

export function GetDirectoryState(arg1:string):Promise<main.DirectoryState>;

export function GetFileInfo(arg1:string):Promise<main.FileDisplayInfo>;

export function OnExit():Promise<void>;

export function OnReady():Promise<void>;

export function Search(arg1:string,arg2:boolean):Promise<Array<search.LocalSearchResult>>;

export function SetFolderVisibility(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SetFolderWatchStatus(arg1:string,arg2:boolean):Promise<void>;
