// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectoryState(arg1) {
  return window['go']['main']['App']['GetDirectoryState'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function OnExit() {
  return window['go']['main']['App']['OnExit']();
}

export function OnReady() {
  return window['go']['main']['App']['OnReady']();
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SetFolderVisibility(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetFolderVisibility'](arg1, arg2, arg3);
}

export function SetFolderWatchStatus(arg1, arg2) {
  return window['go']['main']['App']['SetFolderWatchStatus'](arg1, arg2);
}
